### ISSUE TITLE
Please don't use the `contrib-` prefix

### ISSUE THREAD

**Issue by arthurvr** [darthwade/grunt-environment#3]
`grunt-contrib-*` is a special naming convention the grunt team uses to mark plugins which they create themselves. From [the guidelines](http://gruntjs.com/creating-plugins#naming-your-task):

> The `grunt-contrib` namespace is reserved for tasks maintained by the Grunt team, please name your task something appropriate that avoids that naming scheme.

So I'd suggest you to rename your task. This has been a reason to blacklist plugins from the `gruntjs.com` site as well.

_Please see https://github.com/gruntjs/gruntjs.com/pull/160_

**Comment by arthurvr** [comment]
Friendly ping @darthwade

**Comment by arthurvr** [comment]
Why did you close this, @darthwade? It's still alive: https://www.npmjs.com/package/grunt-contrib-environment.

**Comment by darthwade** [comment]
Done
